#include "/EGP/ScreenPass/pre.ush"

//Hint to Materials which shader we're running in.
#define GOL_PASS_DISPLAY 1

#include "/EGP/ScreenPass/post.ush"


float4 Main(in FTexCoordsVSToPS materialInterpolants,
	  	    in float4 svPos : SV_Position) : SV_Target0
{	
	//Set up the Material code.
	FPixelMaterialInputs matInputs;
	FMaterialPixelParameters matParams;
	ScreenPassSetupPS(svPos, materialInterpolants, matInputs, matParams);

	//Let the user decide how to sample and display the effect.
	return float4(GetMaterialEmissive(matInputs), 1.0);
}