#include "/SnkeOS/ScreenPass/pre.ush"

//Hint to Materials which shader we're running in.
#define GOL_PASS_INIT 1

#include "/SnkeOS/ScreenPass/post.ush"


void Main(in FTexCoordsVSToPS materialInterpolants,
		  in float4 svPos : SV_Position,
		  out float2 newState : SV_Target0)
{
	//Set up the Material code.
	FPixelMaterialInputs matInputs;
	FMaterialPixelParameters matParams;
	ScreenPassSetupPS(svPos, materialInterpolants, matInputs, matParams);

	//Read the starting state from the Material, through its emissive color pin.
	newState.xy = GetMaterialEmissive(matInputs).rg;

	//The first channel is supposed to be a discrete bool.
	newState.x = step(0.5, newState.y);
}