#include "/SnkeOS/ScreenPass/pre.ush"

//Hint to Materials which shader we're running in.
#define GOL_PASS_SIMULATE 1

#include "/SnkeOS/ScreenPass/post.ush"


float DeltaSeconds;
#define SimStateTex PostProcessInput_0_Texture
RWTexture2D<float2> NextSimStateTex;

[numthreads(SIM_GROUP_SIZE_X, SIM_GROUP_SIZE_Y, SIM_GROUP_SIZE_Z)]
void Main(uint3 threadIdx : SV_DispatchThreadID)
{
	uint2 resolution;
	SimStateTex.GetDimensions(resolution.x, resolution.y);

	uint2 pixel = threadIdx.xy;
	float2 uv = (float2(pixel) + 0.5) / float2(resolution);
	if (any(pixel >= resolution))
		return;
	
	//Set up the Material code.
	FPixelMaterialInputs matInputs;
	FMaterialPixelParameters matParams;
	ScreenPassSetupCS(pixel, uv,
					  //Fake "world pos" and "fragment depth":
					  float3((uv * 2) - 1, 0), 0.0,
					  matInputs, matParams);

	//Query the GoL rules from the Material,
	//    interpreting its three Emissive outputs as various living/dying thresholds.
	float3 matOutputs = GetMaterialEmissive(matInputs);
	const float ThresholdTooFew = matOutputs.x,
				ThresholdResurrect = matOutputs.y,
				ThresholdTooMany = matOutputs.z;
	const float OverallSpeed = 0.3;
	
	//Sample the neighboring cell states.
	float2 prevStates[9];
	const int ourIdx = 4;
	for (int x = -1; x <= 1; ++x)
		for (int y = -1; y <= 1; ++y)
		{
			int2 globalIdx = pixel + int2(x, y);
			int localIdx = (x + 1) + ((y + 1) * 3);
			prevStates[localIdx] = any(bool4(globalIdx < 0, globalIdx >= resolution)) ?
				float2(0, 0) :
				SimStateTex[globalIdx].xy;
		}

	//Count the number of living neighbors surrounding us.
	float neighborStrength = 0;
	const float maxStrength = 8.0;
	for (int i = 0; i < 9; ++i)
		if (i != ourIdx)
			neighborStrength += prevStates[i].x;

	//Apply the usual Game of Life rules to our cell, dying/living/resurrecting
	//    based on how many living neighbors we have.
	//Also calculate a "severity" estimating the strength of the pull towards that value.
	float targetValue, severityT, speedScale;
	if (neighborStrength < ThresholdTooFew)
	{
		//Die off, from underpopulation.
		targetValue = 0;
		severityT = 1.0 - (neighborStrength / ThresholdTooFew);
		speedScale = 1.0;
	}
	else if (neighborStrength < ThresholdResurrect)
	{
		//Maintain current living status, from a normal population.
		targetValue = prevStates[ourIdx].x;
		severityT = 1.0;
		speedScale = 1.0;
	}
	else if (neighborStrength <= ThresholdTooMany)
	{
		//Come alive, from an ideal population.
		targetValue = 1;
		severityT = (neighborStrength - ThresholdResurrect) / max(0.0001, ThresholdTooMany - ThresholdResurrect);
		speedScale = 1.0;
	}
	else
	{
		//Die, from overpopulation.
		targetValue = 0;
		severityT = (neighborStrength - ThresholdTooMany) / max(0.0001, maxStrength - ThresholdTooMany);
		speedScale = 1.0;
	}

	//Our cell has two state values: the actual, discrete living/dead bool
	//    and a continuous alternative that moves towards the discrete target.
	//Now that we know the bool value, update the continuous value accordingly.
	float smoothValue = prevStates[ourIdx].y;
	float frameSpeed = DeltaSeconds * max(OverallSpeed * 0.05, speedScale * severityT * OverallSpeed),
		  frameVelocity = frameSpeed * sign(targetValue - smoothValue);
	if (distance(smoothValue, targetValue) < frameSpeed)
		smoothValue = targetValue;
	else
		smoothValue += frameVelocity;

	NextSimStateTex[pixel] = float2(targetValue, smoothValue);
}